#!/bin/bash

echo "🔧 Munus Environment Variables Generator (MongoDB Setup)"
echo "======================================================"
echo ""

# Generate SECRET_KEY
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")

echo "📋 REQUIRED Environment Variables for Render (MongoDB Setup):"
echo "============================================================"
echo ""
echo "🔐 SECURITY:"
echo "SECRET_KEY=$SECRET_KEY"
echo "ALGORITHM=HS256"
echo "ACCESS_TOKEN_EXPIRE_MINUTES=30"
echo "REFRESH_TOKEN_EXPIRE_DAYS=7"
echo ""
echo "🗄️ DATABASE (MongoDB - Primary):"
echo "MONGODB_URI=mongodb+srv://your-username:your-password@your-cluster.mongodb.net/munus"
echo "MONGODB_DB_NAME=munus"
echo ""
echo "🌐 CORS:"
echo 'BACKEND_CORS_ORIGINS=["https://www.gomunus.com","https://gomunus.com","https://munus-nu.vercel.app"]'
echo ""
echo "⚙️ ENVIRONMENT:"
echo "ENVIRONMENT=production"
echo "DEBUG=false"
echo "API_V1_STR=/api/v1"
echo "PROJECT_NAME=Munus API"
echo "VERSION=1.0.0"
echo ""
echo "🤖 AI SERVICES (Optional but Recommended):"
echo "OPENAI_API_KEY=sk-your-openai-api-key-here"
echo ""
echo "📧 EMAIL (Optional):"
echo "MAIL_USERNAME=your-email@gmail.com"
echo "MAIL_PASSWORD=your-app-password"
echo "MAIL_FROM=your-email@gmail.com"
echo "MAIL_PORT=587"
echo "MAIL_SERVER=smtp.gmail.com"
echo "MAIL_FROM_NAME=Munus"
echo ""
echo "📱 TWILIO SMS (Optional):"
echo "TWILIO_ACCOUNT_SID=your-twilio-account-sid"
echo "TWILIO_AUTH_TOKEN=your-twilio-auth-token"
echo "TWILIO_VERIFY_SID=your-twilio-verify-sid"
echo "TWILIO_PHONE_NUMBER=your-twilio-phone-number"
echo ""
echo "☁️ GOOGLE CLOUD (For Google Drive Integration):"
echo "GOOGLE_CLIENT_ID=your-google-client-id-here"
echo "GOOGLE_CLIENT_SECRET=your-google-client-secret-here"
echo ""
echo "📁 FILE STORAGE (Optional - AWS S3):"
echo "AWS_ACCESS_KEY_ID=your-aws-access-key"
echo "AWS_SECRET_ACCESS_KEY=your-aws-secret-key"
echo "AWS_BUCKET_NAME=your-s3-bucket-name"
echo "AWS_REGION=us-east-1"
echo ""
echo "📝 INSTRUCTIONS:"
echo "1. Copy each variable above"
echo "2. Paste it in Render's Environment Variables section"
echo "3. Replace placeholder values with your actual credentials"
echo ""
echo "🔗 Quick Links:"
echo "- MongoDB Atlas: https://cloud.mongodb.com"
echo "- OpenAI API: https://platform.openai.com/api-keys"
echo "- Twilio: https://console.twilio.com"
echo "- Google Cloud Console: https://console.cloud.google.com"
echo "- AWS S3: https://aws.amazon.com/s3/"
echo ""
echo "⚠️  IMPORTANT:"
echo "- Keep your SECRET_KEY and API keys secure"
echo "- Never commit these values to your repository"
echo "- Use different keys for development and production"
echo ""
echo "🎯 PRIORITY ORDER:"
echo "1. SECRET_KEY + MONGODB_URI (Required for basic functionality)"
echo "2. OPENAI_API_KEY (For AI features)"
echo "3. GOOGLE_CLIENT_ID + SECRET (For Google Drive import)"
echo "4. AWS S3 (For file storage)"
echo "5. Email/SMS (For notifications)"
echo ""
echo "💡 NOTE: This setup uses MongoDB as the primary database."
echo "   Supabase is not needed for this configuration." 